### ISSUE TITLE
Logo Design for Android Academy

### ISSUE THREAD

**Issue by baranpirincal** [gcorso/android_academy#1]
Hello!

I am graphic designer and I want to support open-source projects in field of graphics. If you want to re-design your logo design, I can do it. I can show my portfolio too.

What do you think about that?

I am waiting your comment!

Best Regards
Baran Pirinçal

**Comment by gcorso** [comment]
Sure! All contributions are welcome!

In case consider that Android icons should be 512 x 512 32-bit PNG (with alpha).

**Comment by baranpirincal** [comment]
Do you have an idea about what logo design should include or color palette or something like that?

**Comment by gcorso** [comment]
The app main color is blue (#021bbe) so it should probably include some kind of blue. Also, it should include some reference to the fact that it contains digital courses. You might want to take inspiration from the attached logo which is from Cyber Academy an app made based on this project.
![logo](https://user-images.githubusercontent.com/22794353/45253093-2cce9f00-b359-11e8-981a-d4296d924e7f.png)

Its background was created using this [tool](https://romannurik.github.io/AndroidAssetStudio/icons-launcher.html).
